### PR TITLE
RimWorld 1.1 update

### PR DESCRIPTION
**Pull request by LoonyLadle**
Pulling updates from Maaxar's fork.

### CODE REVIEW

**Comment by ImportTaste** [comment]
Hello, I really enjoy the simplicity of your mods. It seems like Maaxar has forked 10 of your mods, will you be incorporating all of them or are you only going to be updating this one?

I personally hope development on all of them continues, though this one in particular holds a special place in my heart. I feel like having special animal prosthetics that are cheaper doesn't make a lot of sense, sometimes you should feel like you can't afford to treat Fido, a case of sentimentality vs. practicality, and the simplicity of this mod achieves that very nicely.

**Comment by LoonyLadle** [comment]
Hello ImportTaste! I'm glad you enjoy the simplicity of my mods; I feel so many people try far too hard to incorporate every cool idea they can think of. Yes, I do plan in incorporating and updating all of my mods as soon as I can find the time to learn how the new mod format works. It appears I need to relearn quite a bit for 1.1!

**Comment by ImportTaste** [comment]
You define the paths you want to use for each version with the file 'LoadFolder.xml' in the root directory.

The simplest solution is to use this:
```xml
<loadFolders>
	<v1.0>
		<li>1.0</li>
	</v1.0>
	<v1.1>
		<li>1.1</li>
	</v1.1>
</loadFolders>
```
and put all the old files (other than About) in a folder named 1.0, and all the new files in a folder named 1.1

As for About.xml, here's an example that uses the new format:
```xml
<?xml version="1.0" encoding="utf-8"?>
<ModMetaData>
	<name>Animals Logic</name>
	<packageId>Oblitus.AnimalsLogic</packageId>
	<author>Oblitus</author>
	<supportedVersions>
		<li>0.19</li>
		<li>1.0</li>
		<li>1.1</li>
	</supportedVersions>
	<modDependenciesByVersion>
		<v1.1>
			<li>
				<packageId>brrainz.harmony</packageId>
				<displayName>Harmony</displayName>
				<steamWorkshopUrl>steam://url/CommunityFilePage/2009463077</steamWorkshopUrl>
				<downloadUrl>https://github.com/pardeike/HarmonyRimWorld/releases/latest</downloadUrl>
			</li>
		</v1.1>
	</modDependenciesByVersion>
	<description>[*] Tags trained animals in caravan and trade interfaces.
[*] Egg-layers will try to find a bed (or any other type of animal sleeping spots) in their allowed area to lay an egg. Unforbids eggs laid outside the home area.
[*] Improved task change responsiveness for animals.
[*] Animals can own beds.
[*] Animal beds can be medical.
[*] (Optional) Medical emergency alerts for animals.
[*] (Optional) Configurable animal hauling efficiency.
[*] (Optional) Configurable tameness decay threshold.
[*] (Optional) Configurable training decay speed.
[*] (Optional) Converts any ruined eggs into unfertilized chicken eggs.
[*] (Optional, default off) Converts any generic meat into chicken meat upon butchering.
[*] (Optional) Predators hunting your pawns (human-like or animals) will be considered hostile by all your pawns and turrets.
[*] (Optional) Prevents animals from eating random stuff.</description>
	<url>https://ludeon.com/forums/index.php?topic=34628</url>
</ModMetaData>
```

You MUST have a `packageId` node and this should be something that never changes, a lot of people make the mistake of putting a version number in their package id, but since mod loading is done through package ids now, this will just cause the mod to fall off the mod list every time it's changed.

**Comment by ImportTaste** [comment]
Addendum: 1.0 was actually updated to be compatible with this format, so don't worry about breaking compatibility with that.

**Comment by ImportTaste** [comment]
Oh, actually this doesn't showcase a very important node you should use, since all dependencies are required, use loadAfter for optional integrations, like this:
```xml
	<loadAfter>
		<li>Rah.RBSEHC</li>
		<li>Rah.RBSE</li>
	</loadAfter>
```

**Pull request merged**
